<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 124e82fa65d90f2eabcf411e300c55f76ff06e29
version: 2
jobs:
  build:
    working_directory: ~/clinicapp2
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
<<<<<<< HEAD
          path: app/build/test-results
=======
          path: app/build/test-results
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 10e7b2b35b74e8c4652750815f5c902b37b5e8c7
#
# Build configuration for Circle CI
#

general:
  artifacts:
<<<<<<< HEAD
    - /home/ubuntu/clinicapp2/app/build/outputs/apk/
=======
    - /home/ubuntu/your-app-name/app/build/outputs/apk/
>>>>>>> 10e7b2b35b74e8c4652750815f5c902b37b5e8c7

machine:
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
  override:
<<<<<<< HEAD
    - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-29.0.2,android-29,extra-google-m2repository,extra-google-google_play_services,extra-android-support
=======
    - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-21.1.2,android-21,extra-google-m2repository,extra-google-google_play_services,extra-android-support
>>>>>>> 10e7b2b35b74e8c4652750815f5c902b37b5e8c7
    - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
  override:
    - (./gradlew assemble):
<<<<<<< HEAD
        timeout: 360
=======
        timeout: 360
=======
<<<<<<< HEAD

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
=======
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
>>>>>>> d3627a3eb309eb827b8fbb36451e84130498bb4f
>>>>>>> 13acf58ecba74e7061cbdd1d1ba590115429ecd4
>>>>>>> 10e7b2b35b74e8c4652750815f5c902b37b5e8c7
>>>>>>> 82865bfd9362cb3a3a01942b7d11c378f31a2989
>>>>>>> 124e82fa65d90f2eabcf411e300c55f76ff06e29
